### ISSUE TITLE
Erro ao correr método não estático

### ISSUE THREAD

**Issue by afmfe-iul** [andre-santos-pt/pandionj#1]
Passos para reproduzir:
1. Criar método estático
2. Correr uma vez o código (ctrl-r)
3. Mudar o código do método para não estático
4. Em vez de correr o código de novo, inserir um novo argumento no mesmo método do ponto 1, visto que este se mantém na view do pandion 

Mensagem de erro para o método getDouble():
`javassist.CannotCompileException: [source error] getDouble is not static
	at javassist.CtBehavior.insertAfter(CtBehavior.java:877)
	at javassist.CtBehavior.insertAfter(CtBehavior.java:792)
	at pt.iscte.pandionj.agent.PandionJAgent$1.transform(PandionJAgent.java:88)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
Caused by: compile error: getDouble is not static
	at javassist.compiler.MemberCodeGen.atMethodCallCore2(MemberCodeGen.java:657)
	at javassist.compiler.MemberCodeGen.atMethodCallCore(MemberCodeGen.java:586)
	at javassist.compiler.MemberCodeGen.atCallExpr(MemberCodeGen.java:537)
	at javassist.compiler.JvstCodeGen.atCallExpr(JvstCodeGen.java:244)
	at javassist.compiler.ast.CallExpr.accept(CallExpr.java:46)
	at javassist.compiler.JvstCodeGen.atMethodArgs(JvstCodeGen.java:358)
	at javassist.compiler.MemberCodeGen.atMethodCallCore(MemberCodeGen.java:569)
	at javassist.compiler.MemberCodeGen.atCallExpr(MemberCodeGen.java:537)
	at javassist.compiler.JvstCodeGen.atCallExpr(JvstCodeGen.java:244)
	at javassist.compiler.ast.CallExpr.accept(CallExpr.java:46)
	at javassist.compiler.MemberCodeGen.atCallExpr(MemberCodeGen.java:510)
	at javassist.compiler.JvstCodeGen.atCallExpr(JvstCodeGen.java:244)
	at javassist.compiler.ast.CallExpr.accept(CallExpr.java:46)
	at javassist.compiler.CodeGen.atBinExpr(CodeGen.java:984)
	at javassist.compiler.ast.BinExpr.accept(BinExpr.java:41)
	at javassist.compiler.JvstCodeGen.atMethodArgs(JvstCodeGen.java:358)
	at javassist.compiler.MemberCodeGen.atMethodCallCore(MemberCodeGen.java:569)
	at javassist.compiler.MemberCodeGen.atCallExpr(MemberCodeGen.java:537)
	at javassist.compiler.JvstCodeGen.atCallExpr(JvstCodeGen.java:244)
	at javassist.compiler.ast.CallExpr.accept(CallExpr.java:46)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:338)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.Javac.compileStmnt(Javac.java:567)
	at javassist.CtBehavior.insertAfterAdvice(CtBehavior.java:892)
	at javassist.CtBehavior.insertAfter(CtBehavior.java:851)
	... 17 more
Error: Main method not found in class aula01.Functions, please define the main method as:
   public static void main(String[] args)
or a JavaFX application class must extend javafx.application.Application`

**Comment by andre-santos-pt** [comment]
Adicionei uma verificação no painel de invocação para garantir que o ficheiro do método não foi alterado entre a abertura do painel e a invocação.
